[build]
  command = "VITE_BACKSTITCH_API_URL=\"http://24.199.97.236:3000/\" npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

